CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ';'
field_optionally_enclosed_by='"'
SKIP_HEADER = 1
DATE_FORMAT = 'DD.MM.YY';

CREATE OR REPLACE PIPE load_from_stage_h_nation
AUTO_INGEST = FALSE AS
    COPY INTO EPAM_LAB.CORE_DWH.NATION
    FROM @EPAM_LAB.CORE_DWH.STAGE
    PATTERN = 'h_nation.csv'
    FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE PIPE load_from_stage_h_customer
AUTO_INGEST = FALSE AS
    COPY INTO EPAM_LAB.CORE_DWH.CUSTOMER
    FROM @EPAM_LAB.CORE_DWH.STAGE
    PATTERN = 'h_customer.csv'
    FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE PIPE load_from_stage_h_part
AUTO_INGEST = FALSE AS
    COPY INTO EPAM_LAB.CORE_DWH.PART
    FROM @EPAM_LAB.CORE_DWH.STAGE
    PATTERN = 'h_part.csv'
    FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE PIPE load_from_stage_h_partsupp
AUTO_INGEST = FALSE AS
    COPY INTO EPAM_LAB.CORE_DWH.PARTSUPP
    FROM @EPAM_LAB.CORE_DWH.STAGE
    PATTERN = 'h_partsupp.csv'
    FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE PIPE load_from_stage_h_region
AUTO_INGEST = FALSE AS
    COPY INTO EPAM_LAB.CORE_DWH.REGION
    FROM @EPAM_LAB.CORE_DWH.STAGE
    PATTERN = 'h_region.csv'
    FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE PIPE load_from_stage_h_supplier
AUTO_INGEST = FALSE AS
    COPY INTO EPAM_LAB.CORE_DWH.SUPPLIER
    FROM @EPAM_LAB.CORE_DWH.STAGE
    PATTERN = 'h_supplier.csv'
    FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE PIPE load_from_stage_h_lineitem
AUTO_INGEST = FALSE AS
    COPY INTO EPAM_LAB.CORE_DWH.LINEITEM
    FROM @EPAM_LAB.CORE_DWH.STAGE
    PATTERN = 'h_lineitem_[0-9].csv'
    FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE PIPE load_from_stage_h_order
AUTO_INGEST = FALSE AS
    COPY INTO EPAM_LAB.CORE_DWH.ORDERS
    FROM @EPAM_LAB.CORE_DWH.STAGE
    PATTERN = 'h_order_[0-9].csv'
    FILE_FORMAT = CSV_FORMAT;


CREATE OR REPLACE PROCEDURE reload_data_from_stage_to_core_dwh_procedure(message VARCHAR)
RETURNS VARCHAR NOT NULL
LANGUAGE SQL
AS
BEGIN
    CALL create_tables_in_core_dwh('');

    CALL SYSTEM$PIPE_FORCE_RESUME('EPAM_LAB.CORE_DWH.LOAD_FROM_STAGE_H_CUSTOMER');
    CALL SYSTEM$PIPE_FORCE_RESUME('EPAM_LAB.CORE_DWH.LOAD_FROM_STAGE_H_LINEITEM');
    CALL SYSTEM$PIPE_FORCE_RESUME('EPAM_LAB.CORE_DWH.LOAD_FROM_STAGE_H_NATION');
    CALL SYSTEM$PIPE_FORCE_RESUME('EPAM_LAB.CORE_DWH.LOAD_FROM_STAGE_H_ORDER');
    CALL SYSTEM$PIPE_FORCE_RESUME('EPAM_LAB.CORE_DWH.LOAD_FROM_STAGE_H_PART');
    CALL SYSTEM$PIPE_FORCE_RESUME('EPAM_LAB.CORE_DWH.LOAD_FROM_STAGE_H_PARTSUPP');
    CALL SYSTEM$PIPE_FORCE_RESUME('EPAM_LAB.CORE_DWH.LOAD_FROM_STAGE_H_REGION');
    CALL SYSTEM$PIPE_FORCE_RESUME('EPAM_LAB.CORE_DWH.LOAD_FROM_STAGE_H_SUPPLIER');

    RETURN 'Tables in CORE_DWH were created and populated with data from STAGE.';
END;


CREATE OR REPLACE TASK reload_data_from_stage_to_core_dwh
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0,30 * * * * UTC' -- Runs at the start and 30th minute of every hour
AS
  CALL reload_data_from_stage_to_core_dwh_procedure();