CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ';'
field_optionally_enclosed_by='"'
SKIP_HEADER = 1
DATE_FORMAT = 'DD.MM.YY';


COPY INTO EPAM_LAB.CORE_DWH.NATION
FROM @EPAM_LAB.CORE_DWH.STAGE
FILES = ('h_nation.csv')
FILE_FORMAT = CSV_FORMAT;

COPY INTO EPAM_LAB.CORE_DWH.CUSTOMER
FROM @EPAM_LAB.CORE_DWH.STAGE
FILES = ('h_customer.csv')
FILE_FORMAT = CSV_FORMAT;

COPY INTO EPAM_LAB.CORE_DWH.PART
FROM @EPAM_LAB.CORE_DWH.STAGE
FILES = ('h_part.csv')
FILE_FORMAT = CSV_FORMAT;

COPY INTO EPAM_LAB.CORE_DWH.PARTSUPP
FROM @EPAM_LAB.CORE_DWH.STAGE
FILES = ('h_partsupp.csv')
FILE_FORMAT = CSV_FORMAT;

COPY INTO EPAM_LAB.CORE_DWH.REGION
FROM @EPAM_LAB.CORE_DWH.STAGE
FILES = ('h_region.csv')
FILE_FORMAT = CSV_FORMAT;

COPY INTO EPAM_LAB.CORE_DWH.SUPPLIER
FROM @EPAM_LAB.CORE_DWH.STAGE
FILES = ('h_supplier.csv')
FILE_FORMAT = CSV_FORMAT;

COPY INTO EPAM_LAB.CORE_DWH.PART
FROM @EPAM_LAB.CORE_DWH.STAGE
FILES = ('h_part.csv')
FILE_FORMAT = CSV_FORMAT;

COPY INTO EPAM_LAB.CORE_DWH.LINEITEM
FROM @EPAM_LAB.CORE_DWH.STAGE
PATTERN = 'h_lineitem_[0-9].csv'
FILE_FORMAT = CSV_FORMAT;

COPY INTO EPAM_LAB.CORE_DWH.ORDERS
FROM @EPAM_LAB.CORE_DWH.STAGE
PATTERN = 'h_order_[0-9].csv'
FILE_FORMAT = CSV_FORMAT;